### ISSUE TITLE
Major Security Vulnerability: Database Connections and Passwords Exposed in Public Repository

### ISSUE THREAD

**Issue by jjboy55** [Tegacreatives/viralhubster-server#1]
**Description**: Hi Tega,

I wanted to bring to your attention a critical security issue I've noticed in your repository. It appears that the postgres database connections and passwords have been committed to the public repository, which exposes sensitive information to anyone accessing this code.

Details:

**Files/Paths Affected**: `config.env`

**Sensitive Information**: PORT, PG_DB, PG_PASSWORD, DB_HOST and so on......

**Impact**: Exposing such sensitive data publicly can lead to unauthorized access to your database, data breaches, and other security risks. It is crucial to address this issue immediately to protect your system and data.

Also consider containerising the application to enable more secure port usage.
I can see you are using an express-node application so you can visit : 
[Express-Node-Docker](https://code.visualstudio.com/docs/containers/quickstart-node)

I suggest you restart the project with different credentials and delete the previous instances of your db model

**Comment by Tegacreatives** [comment]
Thanks for bringing it to my attention, I'm just using the credentials there for testing purpose and would replace it later on for now I'm not worried about the security, thanks also for suggesting containerising the project, I'll be sure to check to incorporate that.

**Comment by jjboy55** [comment]
Ohh alright sorry about that the unnecessary alarm 😅 just thought it was important
